### ISSUE TITLE
[1.0] Device seen offline after successful commissioning with Google Home App

### ISSUE THREAD

**Issue by FutronicsMP** [project-chip/connectedhomeip#23761]
### Reproduction steps

- Nest Hub 2 software version is: 47.9.4.447810048
- Chromecast firmware version: 1.56.324896 
- Google Home App Versoin: 2.60.1.22

- Nordic Light Example from SDK 2.1.2
- Silicon Labs BRD2601B with Matter 1.0 Light example.

After commissioning my device is seen in Google Home App but I cannot control them as device is seen offline (not active in similar way like not powered up). Device is 30cm away from Border Router. Both Phone and Nest Hub 2 are on the same WiFi network. Phone and Nest Hub 2 are using the same google account (e-mail).

I configured aswell google project as described here:
https://developers.home.google.com/matter/project/create

and configured matter integration:
LigtBulb   Light   0xfff1   0x8005

Does anybody have similar Issue? What might be wrong?

Problem exists for both Nordic and Silicon Labs Matter Light Examples. Enclosed please find log file from Matter Device.

### Bug prevalence

Every time after successful commissioning

### GitHub hash of the SDK that was being used

Nordik SDK 2.1.2  supporting Matter 1.0

### Platform

efr32

### Platform Version(s)

1.0

### Type

Test Improvement

### Anything else?

[log matter (1).txt](https://github.com/project-chip/connectedhomeip/files/10092783/log.matter.1.txt)

**Comment by mcreteau** [comment]
Hello
Yes I experience the same issue while using a Matter Bridge commissioned by Google Home app. Bridge is displayed but underlying devices are offline.

**Comment by rochaferraz** [comment]
Hi @FutronicsMP. Thanks for raising the issue. We've identified a relevant cloud flag that hasn't fully rolled out yet that's preventing control. We will work on expediting it, please stand by

**Comment by benjaminnestler** [comment]
Same for me with the Nordic Semiconductor Matter-Template extended with thermostat cluster.

@rochaferraz Is your finding a GHA bug or a bug in the Matter/connectedhomeip repository? Thanks for your great support.

**Comment by doublemis1** [comment]
@FutronicsMP please try to factory reset the nest hub, remove the devices from the Google home app and link the nest once again with Google Home app, and proceed the commissioning (after commissioning Google Home App may need some time - couple seconds to have fully operational device).
I tested that with Nordic, and I saw that after update of Nest Hub firmware I needed to factory reset the Hub.

**Comment by resghst** [comment]
@FutronicsMP could you tell me how to update Nest Hub 2 to version 1.56.324896.
Because my Nest Hub 2 version still stays on 1.56.309385.

**Comment by rochaferraz** [comment]
Hi @FutronicsMP, @benjaminnestler the cloud flag change is published, but it takes several days to take effect on the whole device population, sorry for the temporary down time.

@resghst the hub updates are automatic. The gradual rollout is also true for Nest Hub 2nd gen updates, but please note that only those specific devices of users enrolled in Matter Public Preview will be affected before launch.

**Comment by rochaferraz** [comment]
@FutronicsMP, @benjaminnestler the rollout should have reached 100%. Please try again the commissioning-control on your setups. Thanks!

**Comment by AlexeyYukhin** [comment]
> @FutronicsMP, @benjaminnestler the rollout should have reached 100%. Please try again the commissioning-control on your setups. Thanks!

hi. I also have Google Nest Hub Gen2 and switched development program (testing update program) ON. But it's still on 1.56.309385 chromecast firmware version (47.9.4.447810048 software version).

Is there anything wrong I'm doing?

**Comment by benjaminnestler** [comment]
@AlexeyYukhin I think we have to wait until the update reached our devices :-(

**Comment by oblaser** [comment]
So, it now works for me. Here's what I've done:

1. setup a Matter Integration in the Google Developper Console (Light 0xFFF1 0x8005)
0. enable software preview for GHA and Nest (setting is stored in the cloud and does not get lost on reinstallations or resets)
    - GHA: https://support.google.com/googlenest/answer/12494697?hl=en#zippy=%2Crequest-an-invite%2Chow-to-leave-public-preview
    - Nest: in the nest settings (via the GHA) General > Device Info > Preview Program
0. wait for the software update, maybe a reboot helps (Nest 47.9.4.447810048 1.56.324896 / GHA 2.60.1.22)
0. remove all Matter devices and Nest in GHA
0. reinstall GHA
0. factory reset Nest
0. add Nest to GHA
0. comission device (device stays offline for a couple of seconds)
0. use the device

I don't know if every step is really needed, but it's doing the job.

**Comment by alfonsotames** [comment]
> @FutronicsMP, @benjaminnestler the rollout should have reached 100%. Please try again the commissioning-control on your setups. Thanks!

I've been waiting for 5 or 6 days for the preview update but my Nest 2 still shows firmware 1.56.309385 :(

I tried to factory reset and reboot the device several times and nothing.

I can provision a Matter device but will still appear offline. I'm using nRF 2.1.2.

Is threre something else I need to do besides enrolling in the Preview Program for the Nest 2? I'm baffled.

Thanks,

at

**Comment by alfonsotames** [comment]
The upgrade 1.56.32 hit today before dawn and now it works without having to register the Matter Integration in the Google Developper Console.

**Comment by benjaminnestler** [comment]
Hi @alfonsotames,
same behavior for me and my Google Nest Hub. The firmware update was received in the night. Now the Chromecast firmware version shows 1.56.324896 and my devices (Light bulb example on nrf5340DK and a custom thermostat based on nrf52840 dongle) are shown as online devices and the control of these devices works.

**Comment by benjaminnestler** [comment]
I think we can close this issue ;-) It seems to be solved.

**Comment by Ne01iu** [comment]
The device still show offline in my environment, but work fine in the Apple Home app.
Is there any suggestions?

Nest Hub 2 software version is: 47.9.4.447810048
Chromecast firmware version: 1.56.324896
Google Home App Versoin: 2.60.1.22
Nordic Light Example from SDK 2.1.2
Nordic 52840DK Board

**Comment by BertLammers** [comment]
For me it has worked for a few days after the Nest Hub 2 update to 1.56.324896. But after removing the Matter device and recommissioning it the problem is back. Commissioning works fine but the device is shown offline and cannot be controlled using the Google Home App or the Nest Hub. Controlling it via an iPhone and Homepod works without problems and I am also able to control it using the google sample app for matter (https://github.com/google-home/sample-app-for-matter-android).

**Comment by alfonsotames** [comment]
Try rebooting your devices. I also have encountered strange behavior when
removing and adding devices again. They appear offline but after some
reboots and waiting they appear again online.

I'm using nrf 2.1.2 and nest 2nd gen on preview 1.56.324896.

all the best,

at

**Comment by cw-20021349** [comment]
hi 

After Google Nest hub 2th generation new firmware release on 12/13, Nethub 2th firmware was updated.
(https://support.google.com/googlenest/answer/7365257?hl=en#zippy=%2Ccurrent-preview-program-firmware-version)

And I checked the release notes on 12/15 and configured the environment for the Matter 1.0 test.
(https://developers.home.google.com/matter/release-notes)

But it doesn't pair with the thread module. My thread module is a Light bulb sample model.
Prior to the Matter 1.0 update, it paired normally.

My Developer Console 
https://drive.google.com/file/d/1njXeuUD9bBvl7k8SI6NhQSHJsPNH9H4z/view?usp=sharing

reproduce video
https://drive.google.com/file/d/1TRbETcwY6YJobEYTo2NUoVxXFOSL9_ca/view?usp=sharing

Google Nest hub 2th fw version
https://drive.google.com/file/d/1YNPXQSOzReG6HJFs2ZRZV0O943MyQVhk/view?usp=sharing

issue log
https://drive.google.com/file/d/1sX0YCvFKEOkW_n-Tl7-wImFNqq0gTxwF/view?usp=share_link

Please advise on this matter.

**Comment by dhrishi** [comment]
@cw-20021349 I checked the phone app logs you've shared. This is a known regression from Google side in their latest update. We have already reported it to them. I will post when there is a fix available.

**Comment by cw-20021349** [comment]
@dhrishi 

https://www.googlenestcommunity.com/t5/Smart-Home-Developer-Forum/No-pairing-after-Google-Nest-2th-Matter-1-0-update/td-p/315260

According to the community's answer above, there are multiple projects in the Google Developer Console? is said to occur.

I actually tested by deleting all the projects and recreating just one project, but it still doesn't pair.

Do you think the project issues in the developer console are correct?

**Comment by dhrishi** [comment]
@cw-20021349 The issue has been fixed now. We can get the commissioning using Google Home functional

**Comment by cw-20021349** [comment]
@dhrishi 
hi
Commissioning was successful last Friday. thank you

**Comment by alfonsotames** [comment]
Is it me or it's again broken?

**Comment by FHFS** [comment]
> Is it me or it's again broken?

I have had a similar problem. I was using the default ProductID(0xfff1) and VendorID(0x8005) for my nRF52840 device. I had a different vendorid(0xfff4) and productid(0xBEEF) on [DeveloperConsole](https://console.home.google.com/projects/my-project/matter)

I was unable to commission my device after removing it.

After I added the correct productid and vendorid to the developerconsole I was able to add my devices again.
