### ISSUE TITLE
[BUG] [TC-SC-4.3] failed due to error 'NoneType' object has no attribute 'txt_record'

### ISSUE THREAD

**Issue by YuanWangSE** [project-chip/connectedhomeip#38974]
### Reproduction steps

Execute the case in TH UI, then download the log.

*
* Test test_TC_SC_4_3 failed for the following reason:
* 'NoneType' object has no attribute 'txt_record'
*
* File "/root/python_testing/scripts/sdk/TC_SC_4_3.py", line 284, in test_TC_SC_4_3
* AttributeError: 'NoneType' object has no attribute 'txt_record'
*
* Test step:
*     7: TH performs a query for the TXT record against the qname instance_qname.	Expected outcome: Verify TXT record is returned
*
* Endpoint: None
*

### Bug prevalence

always

### GitHub hash of the SDK that was being used

a12250a4e4ffce5be5f809479fbe8d85e5acd230

### Platform

windows

**Comment by pankore** [comment]
Hi, thank you for raising this issue.

I’m also encountering the same error when executing the UI Python test case in the TH using the default PICS files for the Raspberry Pi platform provided by QA in https://groups.csa-iot.org/wg/matter-csg/document/39613. The error persists when commissioning with the chip-all-cluster-app, and my test results align using my own DUT and TH having the same result with chip-all-cluster-app. For clarity and easier debugging, I’ve attached the relevant TH log and chip-all-cluster-app log during commissioning with the TH.
Thank you.

[TC-SC-4.3_allClusterApp.txt](https://github.com/user-attachments/files/20591169/TC-SC-4.3_allClusterApp.txt)

Test test_TC_SC_4_3 failed for the following reason:
Test Step 10 : TH performs a DNS-SD browse for _I<hhhh>._sub._matter._tcp.local, where <hhhh> is the 64-bit compressed Fabric identifier, expressed as a fixed-length, sixteencharacter hexadecimal string, encoded as ASCII (UTF-8) text using capital letters.
[MatterTest] 06-04 12:04:23.877 INFO MDNS discovered service types: ['_device-info._tcp.local.', '_matterd._udp.local.', '_smb._tcp.local.']
[MatterTest] 06-04 12:04:23.881 ERROR Exception occurred in test_TC_SC_4_3.

**Comment by z-tdy** [comment]
During 1.4.2 SVE run into the same problem.
Could be the cause at step 6 ? =>> when network is unreachable?

[running steps manually - all passed]


[MatterTest] 06-19 13:03:42.744 INFO ***** Test Step 6 : TH performs a query for the SRV record against the qname instance_qname.
[MatterTest] 06-19 13:03:42.750 INFO 
Looking for MDNS service type '_matter._tcp.local.',  service name '5C58A2C38BA819CB-0000000012344321._matter._tcp.local.', record type 'SRV'

[MatterTest] 06-19 13:03:42.799 WARNING Error with socket 23 (('fd11:db8:1::1', 5353, 0, 0))): [Errno 101] Network is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 1276, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network is unreachable
[MatterTest] 06-19 13:03:42.801 WARNING Error with socket 26 (('::1', 5353, 0, 0))): [Errno 101] Network is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 1276, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network is unreachable
Requesting MDNS SRV record...
[MatterTest] 06-19 13:03:43.262 INFO Discovery data:
{
    "_matter._tcp.local.": [
        {
            "service_name": "5C58A2C38BA819CB-0000000012344321._matter._tcp.local.",
            "instance_name": "5C58A2C38BA819CB-0000000012344321",
            "server": "26904EA67B09E8A7.local.",
            "port": 5540,
            "addresses": [
                "fd11:22::4651:b4f5:342f:290d"
            ],
            "txt_record": {},
            "priority": 0,
            "interface_index": null,
            "weight": 0,
            "host_ttl": 120,
            "other_ttl": 4500,
            "service_type": "_matter._tcp.local."
        }
    ]
}
[MatterTest] 06-19 13:03:43.262 INFO ***** Test Step 7 : TH performs a query for the TXT record against the qname instance_qname.
[MatterTest] 06-19 13:03:43.263 INFO 
Looking for MDNS service type '_matter._tcp.local.',  service name '5C58A2C38BA819CB-0000000012344321._matter._tcp.local.', record type 'TXT'

Requesting MDNS TXT record...
Requesting MDNS TXT record...
Requesting MDNS TXT record...
Requesting MDNS TXT record...
Requesting MDNS TXT record...
[MatterTest] 06-19 13:03:47.293 INFO Discovery data:
{
    "_matter._tcp.local.": []
}
[MatterTest] 06-19 13:03:47.294 ERROR Exception occurred in test_TC_SC_4_3.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/mobly/base_test.py", line 801, in exec_one_test
    test_method()
  File "/usr/local/lib/python3.12/dist-packages/chip/testing/decorators.py", line 254, in async_runner
    return _async_runner(body, self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/chip/testing/decorators.py", line 242, in _async_runner
    return test_instance.event_loop.run_until_complete(asyncio.wait_for(body(test_instance, *args, **kwargs), timeout=timeout))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/root/python_testing/scripts/sdk/TC_SC_4_3.py", line 284, in test_TC_SC_4_3
    txt_record_returned = operational_record.txt_record is not None and bool(operational_record.txt_record)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'txt_record'
[MatterTest] 06-19 13:03:47.300 ERROR 

******************************************************************
*
* Test test_TC_SC_4_3 failed for the following reason:
* 'NoneType' object has no attribute 'txt_record'
*
* File "/root/python_testing/scripts/sdk/TC_SC_4_3.py", line 284, in test_TC_SC_4_3
* AttributeError: 'NoneType' object has no attribute 'txt_record'
*
* Test step:
*     7: TH performs a query for the TXT record against the qname instance_qname.	Expected outcome: Verify TXT record is returned
*
* Endpoint: None
*
*******************************************************************

**Comment by cecille** [comment]
https://github.com/project-chip/connectedhomeip/pull/39623 - fix linked here. Please review.

**Comment by raul-marquez-csa** [comment]
Closed as fix has been merged

**Comment by Sandyyeow-realtek** [comment]
Hi, I attempted to retest the chip-all-cluster-app using the updated test script available at https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_SC_4_3.py. 
Unfortunately, the error persists. The test still fails during commissioning with the chip-all-cluster-app, and the test results are  consistent when using my own DUT along with the updated test script.

To assist investigation, I’ve attached the relevant logs:

[TC-SC-4.3.zip](https://github.com/user-attachments/files/21361128/TC-SC-4.3.zip)

Failure point: 
Test test_TC_SC_4_3 failed for at Test Step 10 : TH performs a DNS-SD browse for _I._sub._matter._tcp.local, where is the 64-bit compressed Fabric identifier, expressed as a fixed-length, sixteencharacter hexadecimal string, encoded as ASCII (UTF-8) text using capital letters.

Thank you.
